version: 2

jobs:
  flake8:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout
      - run: sudo pip install tox
      - restore_cache:
         keys:
           - v1-tox-{{ checksum "tox.ini" }}-{{ checksum "requirements.txt" }}
      - run: tox --notest
      - save_cache:
         key: v1-tox-{{ checksum "tox.ini" }}-{{ checksum "requirements.txt" }}
         paths:
           - .tox
      - run: tox -e flake8

  isort:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout
      - run: sudo pip install tox
      - restore_cache:
         keys:
           - v1-tox-{{ checksum "tox.ini" }}-{{ checksum "requirements.txt" }}
      - run: tox --notest
      - save_cache:
         key: v1-tox-{{ checksum "tox.ini" }}-{{ checksum "requirements.txt" }}
         paths:
           - .tox
      - run: tox -e isort

  tests:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout
      - run: sudo pip install tox
      - restore_cache:
         keys:
           - v1-tox-{{ checksum "tox.ini" }}-{{ checksum "requirements.txt" }}
      - run: tox --notest
      - save_cache:
         key: v1-tox-{{ checksum "tox.ini" }}-{{ checksum "requirements.txt" }}
         paths:
           - .tox
      - run: tox -e py2-django1_11
      - run: tox -e py3-django1_11
      - run: tox -e py3-django2_1
      - run: tox -e py3-django2_2
      - run: tox -e coverage

workflows:
  version: 2

  build:
    jobs:
      - flake8
      - isort
      - tests
